language: python
# Replace "python" with java if appropriate

python:
  - "2.7"

sudo: required

services:
  - docker

notifications:
#  email:
#    recipients:
#      - username@email.dom
#    on_success: never # default: change
#    on_failure: always # default: always

env:
  global:
#    Please see https://docs.travis-ci.com/user/encryption-keys/ for information
#    about adding encryption keys which can be used to store auth tokens used in running apps against
#    the KBase infrastructure
#    secure: "blahblahblah"

before_install:
    - env

install:
    #- pip install coveralls
    #- pip install coverage
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    # Insert your own module here
    #- git clone https://github.com/kbase/kb_sdk.git
    #- cd kb_sdk
    # run the kb-sdk test command once to build test_local dir and populate the .ignore files
    #- kb-sdk test -s || true
    
script:
  - kb-sdk validate
  
